### ISSUE TITLE
Firebase 연동 오류

### ISSUE THREAD

**Issue by suminute** [suminute/Stylegacy#4]
logger.ts:115 [2023-07-18T08:14:08.396Z]  @firebase/firestore: Firestore (10.0.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=permission-denied]: Permission denied on resource project "stylegacy-e4ba6",.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

process.env로 api key를 받아오면 생기는 오류!

**Comment by muzi55** [comment]
Firebase 프로젝트 설정 확인이랑 
환경 변수 관리  확인해야할거같아여 !

![당신도할수있다리액트](https://github.com/suminute/Stylegacy/assets/132406946/7e309ce9-70f2-4bd9-a1c2-d2dfad185ce1)
